apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: An example of a Backstage application.
  annotations:
    github.com/project-slug: shenxianpeng/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: group:xpshen
  lifecycle: experimental
